export function exportAnalysisJson(analysis, filenamePrefix = "icdf-analysis") {
  const blob = new Blob([JSON.stringify(analysis, null, 2)], {
    type: "application/json;charset=utf-8;",
  });
  downloadBlob(blob, `${filenamePrefix}-${Date.now()}.json`);
}

export function exportAnalysisCsv(analysis) {
  const flat = {
    timestamp: analysis.timestamp || new Date().toISOString(),
    ip_address: analysis.ip_address || "",
    attack: analysis.prediction?.attack || "",
    confidence: analysis.prediction?.confidence ?? "",
    severity: analysis.prediction?.severity ?? "",
    risk_level: analysis.risk?.risk_level || "",
    risk_score: analysis.risk?.risk_score ?? "",
    action: analysis.decision?.action || "",
    country: analysis.abuseipdb?.country || "",
    analysis_id: analysis.analysis_id || analysis._id || "",
  };

  const headers = Object.keys(flat);
  const escape = (value) => {
    const str = value == null ? "" : String(value);
    if (/[",\n]/.test(str)) return `"${str.replace(/"/g, '""')}"`;
    return str;
  };

  const csv = [headers.join(","), headers.map((key) => escape(flat[key])).join(",")].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  downloadBlob(blob, `icdf-analysis-${Date.now()}.csv`);
}

export function exportAnalysisPdf(analysis) {
  const win = window.open("", "_blank", "noopener,noreferrer,width=900,height=700");
  if (!win) return;

  const title = `ICDF Security Report — ${analysis.ip_address || "Analysis"}`;
  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 24px; color: #111; }
          h1 { font-size: 20px; margin-bottom: 4px; }
          h2 { font-size: 14px; margin-top: 20px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
          table { width: 100%; border-collapse: collapse; margin-top: 8px; }
          td { padding: 6px 4px; border-bottom: 1px solid #eee; vertical-align: top; }
          td:first-child { width: 180px; color: #555; }
          .muted { color: #666; font-size: 12px; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p class="muted">Generated by Intelligent Cyber Defense Framework</p>
        <h2>Prediction</h2>
        <table>
          <tr><td>IP Address</td><td>${analysis.ip_address || "—"}</td></tr>
          <tr><td>Attack Type</td><td>${analysis.prediction?.attack || "—"}</td></tr>
          <tr><td>Severity</td><td>${analysis.prediction?.severity ?? "—"}</td></tr>
          <tr><td>Confidence</td><td>${analysis.prediction?.confidence ?? "—"}%</td></tr>
        </table>
        <h2>Risk Assessment</h2>
        <table>
          <tr><td>Risk Score</td><td>${analysis.risk?.risk_score ?? "—"}</td></tr>
          <tr><td>Risk Level</td><td>${analysis.risk?.risk_level || "—"}</td></tr>
        </table>
        <h2>Decision</h2>
        <table>
          <tr><td>RL Action</td><td>${analysis.decision?.action || "—"}</td></tr>
          <tr><td>Status</td><td>${analysis.decision?.status || "—"}</td></tr>
        </table>
      </body>
    </html>
  `;

  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
