function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function exportAnalysisJson(analysis, filenamePrefix = "icdf-analysis") {
  const blob = new Blob([JSON.stringify(analysis, null, 2)], {
    type: "application/json;charset=utf-8;",
  });
  downloadBlob(blob, `${filenamePrefix}-${Date.now()}.json`);
}

export function exportAnalysisCsv(analysis) {
  const flat = {
    timestamp: analysis.timestamp || new Date().toISOString(),
    ip_address: analysis.ip_address || "",
    attack: analysis.prediction?.attack || "",
    confidence: analysis.prediction?.confidence ?? "",
    severity: analysis.prediction?.severity ?? "",
    risk_level: analysis.risk?.risk_level || "",
    risk_score: analysis.risk?.risk_score ?? "",
    action: analysis.decision?.action || "",
    country: analysis.abuseipdb?.country || "",
    analysis_id: analysis.analysis_id || analysis._id || "",
  };

  const headers = Object.keys(flat);
  const escape = (value) => {
    const str = value == null ? "" : String(value);
    if (/[",\n]/.test(str)) return `"${str.replace(/"/g, '""')}"`;
    return str;
  };

  const csv = [headers.join(","), headers.map((key) => escape(flat[key])).join(",")].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  downloadBlob(blob, `icdf-analysis-${Date.now()}.csv`);
}

/**
 * Opens a printable HTML report. Use the browser "Save as PDF" option in the print dialog.
 * Avoids window.open(..., "noopener") which blocks document.write and shows a blank page.
 */
export function exportAnalysisPdf(analysis) {
  const ip = escapeHtml(analysis.ip_address || "Analysis");
  const title = `ICDF Security Report — ${ip}`;
  const attack = escapeHtml(analysis.prediction?.attack || "—");
  const severity = escapeHtml(analysis.prediction?.severity ?? "—");
  const confidence = escapeHtml(analysis.prediction?.confidence ?? "—");
  const riskScore = escapeHtml(analysis.risk?.risk_score ?? "—");
  const riskLevel = escapeHtml(analysis.risk?.risk_level || "—");
  const action = escapeHtml(analysis.decision?.action || "—");
  const status = escapeHtml(analysis.decision?.status || "—");
  const analysisId = escapeHtml(analysis.analysis_id || analysis._id || "—");
  const timestamp = escapeHtml(analysis.timestamp || new Date().toISOString());

  const html = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${title}</title>
    <style>
      body { font-family: Arial, Helvetica, sans-serif; padding: 24px; color: #111; }
      h1 { font-size: 20px; margin: 0 0 4px; }
      h2 { font-size: 14px; margin-top: 20px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
      table { width: 100%; border-collapse: collapse; margin-top: 8px; }
      td { padding: 6px 4px; border-bottom: 1px solid #eee; vertical-align: top; }
      td:first-child { width: 180px; color: #555; }
      .muted { color: #666; font-size: 12px; margin: 0 0 16px; }
      @media print {
        body { padding: 0; }
      }
    </style>
  </head>
  <body>
    <h1>${title}</h1>
    <p class="muted">Generated by Intelligent Cyber Defense Framework · ${timestamp}</p>
    <h2>Prediction</h2>
    <table>
      <tr><td>IP Address</td><td>${ip}</td></tr>
      <tr><td>Attack Type</td><td>${attack}</td></tr>
      <tr><td>Severity</td><td>${severity}</td></tr>
      <tr><td>Confidence</td><td>${confidence}</td></tr>
      <tr><td>Analysis ID</td><td>${analysisId}</td></tr>
    </table>
    <h2>Risk Assessment</h2>
    <table>
      <tr><td>Risk Score</td><td>${riskScore}</td></tr>
      <tr><td>Risk Level</td><td>${riskLevel}</td></tr>
    </table>
    <h2>Decision</h2>
    <table>
      <tr><td>RL Action</td><td>${action}</td></tr>
      <tr><td>Status</td><td>${status}</td></tr>
    </table>
  </body>
</html>`;

  // Prefer a same-origin blob tab so content always renders (noopener-safe).
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank");

  if (!win) {
    URL.revokeObjectURL(url);
    // Popup blocked: fall back to downloadable HTML report.
    downloadBlob(blob, `icdf-analysis-${Date.now()}.html`);
    return;
  }

  const triggerPrint = () => {
    try {
      win.focus();
      win.print();
    } catch {
      // Ignore; user can still print manually from the open tab.
    }
  };

  // Wait for the blob document to load before printing.
  const timer = window.setTimeout(triggerPrint, 400);
  win.addEventListener(
    "load",
    () => {
      window.clearTimeout(timer);
      triggerPrint();
    },
    { once: true }
  );

  // Revoke after print dialog has had time to open.
  window.setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
